name: Windows_CI
on:
  push:
    branches:
      - master
      - main
      - snnn/sdl2
  pull_request:

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  AZCOPY_AUTO_LOGIN_TYPE: MSI
  AZCOPY_MSI_CLIENT_ID: 63b63039-6328-442f-954b-5a64d124e5b4

jobs:
  Onnxruntime-SCA:
    runs-on: ["self-hosted", "1ES.Pool=onnxruntime-github-vs2022-mms"]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: false
      - uses: actions/setup-python@v3
        with:
          python-version: '3.11.x'
          architecture: 'x64'

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Build code
        run: python tools\ci_build\build.py --config Debug --build_dir D:\b --skip_submodule_sync --build_csharp --update --build --parallel --cmake_generator "Visual Studio 17 2022" --build_shared_lib --enable_pybind --cmake_extra_defines onnxruntime_ENABLE_STATIC_ANALYSIS=ON
        
      - name: Generate sarif
        working-directory: D:\b
        run: npx @microsoft/sarif-multitool merge *.sarif --recurse --output-directory=${{ github.workspace }}\output --output-file=MergeResult.sarif --merge-runs && dir ${{ github.workspace }}\output

      - name: Upload SARIF to GitHub
        uses: github/codeql-action/upload-sarif@v2
        continue-on-error: true
        with:
          sarif_file: ${{ github.workspace }}\output\MergeResult.sarif
          category: VS_SCA
